# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

bioc_required: yes
use_bioc: yes
r_check_args: --as-cran

r:
  - release

addons:
  apt:
    packages:
    - tk 
    - tk-dev
    - tcl 
    - tcl-dev

# env:
#   global:
#   - _R_CHECK_FORCE_SUGGESTS_=FALSE
#   - MAKEFLAGS="-j 2"