# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

bioc_required: yes
use_bioc: yes
r_check_args: --as-cran

r:
  - release
  
# tlmgr line added on 7 Jun 2016 as workaround for:
# https://github.com/travis-ci/travis-ci/issues/7863
before_install:
  - tlmgr install xkeyval
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start